# Generated by Django 5.2.8 on 2025-11-09 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_remove_empresa_email_alter_empresa_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
