# Generated by Django 5.2.8 on 2025-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_factura_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
