# Generated by Django 5.2.8 on 2025-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('empresa', 'number'), name='unique_invoice_number_per_empresa'),
        ),
    ]
